# Generated by Django 5.2.7 on 2025-10-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                ("creation_time", models.DateTimeField(auto_created=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=100)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
