# Generated by Django 5.2.7 on 2025-10-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_version"),
    ]

    operations = [
        migrations.RenameField(
            model_name="type",
            old_name="type",
            new_name="name",
        ),
    ]
